[package]
name = "port_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"]  }
dns-lookup = "2.0.4"
futures = "0.3"
reqwest = { version = "0.12.9", features = ["json"] }